### ISSUE TITLE
data-effects-th is incompatible with th-abstraction-0.5.0.0

### ISSUE THREAD

**Issue by jchia** [sayo-hs/data-effects#2]
data-effects-th does not build with th-abstraction-0.5.0.0. The lower bound on data-effects-th should be increased to 0.6.0.0 or the data-effects-th code should to be fixed to be compatible with th-abstraction-0.5.0.0

```
$ git diff
diff --git i/data-effects-th/data-effects-th.cabal w/data-effects-th/data-effects-th.cabal
index 96cb0cb..d221509 100644
--- i/data-effects-th/data-effects-th.cabal
+++ w/data-effects-th/data-effects-th.cabal
@@ -62,7 +62,7 @@ library
         base                    >= 4.16.4 && < 4.21,
         data-effects-core       ^>= 0.2,
         template-haskell        >= 2.18 && < 2.23,
-        th-abstraction          >= 0.4 && < 0.8,
+        th-abstraction          >= 0.4 && < 0.6,
         lens                    >= 5.2.3 && < 5.4,
         mtl                     >= 2.2.2 && < 2.4,
         extra                   ^>= 1.7.14,
$ cabal build data-effects-th
Build profile: -w ghc-9.6.6 -O1
In order, the following will be built (use -v for more details):
 - data-effects-th-0.2.0.0 (lib) (first run)
Preprocessing library for data-effects-th-0.2.0.0...
Building library for data-effects-th-0.2.0.0...
[1 of 5] Compiling Data.Effect.TH.Internal ( src/Data/Effect/TH/Internal.hs, /home/jchia/gh/data-effects/dist-newstyle/build/x86_64-linux/ghc-9.6.6/data-effects-th-0.2.0.0/build/Data/Effect/TH/Internal.o, /home/jchia/gh/data-effects/dist-newstyle/build/x86_64-linux/ghc-9.6.6/data-effects-th-0.2.0.0/build/Data/Effect/TH/Internal.dyn_o ) [Data.Either.Validation package changed]

src/Data/Effect/TH/Internal.hs:94:48: error:
    Module
    ‘Language.Haskell.TH.Datatype.TyVarBndr’
    does not export
    ‘pattern BndrReq’
   |
94 | import Language.Haskell.TH.Datatype.TyVarBndr (pattern BndrReq)
   |                                                ^^^^^^^^^^^^^^^
Error: [Cabal-7125]
Failed to build data-effects-th-0.2.0.0.
```

**Comment by ymdfield** [comment]
Fixed. Thanks!
